title: Borderlands Python SDK

url: https://bl-sdk.github.io
github_username: bl-sdk
repository: bl-sdk/willow2-mod-db

markdown: kramdown
theme: just-the-docs

color_scheme: dev

collections:
  willow2_mods:
    sort-by: title
    permalink: /willow2-mod-db/mods/:name/
  oak_mods:
    sort-by: title
    permalink: /oak-mod-db/mods/:name/

defaults:
  - scope:
      path: ""
      type: willow2_mods
    values:
      layout: mod
  - scope:
      path: ""
      type: oak_mods
    values:
      layout: mod
    scope:
      path: ""
    values:
      has_toc: false

callouts:
  warning:
    title: Warning
    color: red

favicon_ico: /assets/images/favicon.png

plugins:
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  - oak-mod-db
  - willow2-mod-db

nav_external_links:
  - title: BL2/TPS/AoDK Mods
    url: willow2-mod-db/
  - title: BL3/WL Mods
    url: oak-mods-db/
  - title: Modding Support Discord
    url: https://discord.gg/bXeqV8Ef9R
  - title: SDK Developer Discord
    url: https://discord.gg/VJXtHvh
