title: BL2/TPS SDK Mod Database
description: >-
  A list of sdk mods for Borderlands 2, The Pre-Sequel, and the Attack on Dragon Keep standalone.

url: https://bl-sdk.github.io
baseurl: /willow2-mod-db
github_username: bl-sdk
repository: bl-sdk/willow2-mod-db

collections:
  mods:
    output: true
    sort-by: title
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: mods
    values:
      layout: mod

markdown: kramdown
theme: just-the-docs
color_scheme: dark

just_the_docs:
  collections:
    mods:
      name: Mods
callouts:
  warning:
    title: Warning
    color: red

favicon_ico: /assets/images/favicon.png

nav_external_links:
  - title: Modding Support Discord
    url: https://discord.gg/bXeqV8Ef9R
  - title: Latest Release
    url: https://github.com/bl-sdk/willow2-mod-manager/releases/latest

plugins:
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true
